name: Docker
on:
  push:
    branches:
      - master

env:
    IMAGE_NAME: nginx
    IMAGE_TAG: fixed

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPOSITORY_NAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ secrets.DOCKER_REPOSITORY_NAME }}/$IMAGE_NAME:$IMAGE_TAG
